### ISSUE TITLE
For bedrifter maileren i backend må fikses

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/API#115]
Det er noe galt med maileren i backend som må fikses. Dette tilfelle gjelder når vi får informasjon fra "For bedrifter" formet. Buggen ser ut til å kun eksistere i prod og ikke i dev miljøet.

**Comment by treyshotz** [comment]
Det virker ut som problemet har ligget hos drift hele tiden. API'et er nå oppdatert og fungerer.
