### ISSUE TITLE
URL knyttet til notifikasjoner

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/API#118]
- url --> Felt med en URL man skal sendes til når man trykker på en notifikasjon. @superspeed500?

**Comment by superspeed500** [comment]
Ja, stemmer. Dersom en URL er spesifisert vil man kunne trykke på selve notifikasjonen for å gå til den lenken som er spesifisert. Er det ikke noe lenke vil ikke notifikasjonen oppføre seg som en knapp :) Ser ikke noe problem her annet enn et spørsmål som er besvart. Lukker saken.
