### ISSUE TITLE
Gjøre det mulig for HS å endre hvilken undergruppe du er på

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/API#120]
Brukerstory:
Som HS ønsker jeg å kunne endre TIHLDE-medlemmer sin gruppestatus, slik at ved opptak kan jeg legge til nye tihlde-medlemmer i sine respektive grupper. Dette må til slik at f.eks. nok skal ha tilgang til å lage jobbannonser.

---
Backend:
Grupper og tillatelser ligger allerede inne. Må lage et endepunkt i API-et slik at admin kan gi se hvem som er i hver gruppe og leggetil/fjerne medlemmer fra den gruppen

**Comment by Eirsteir** [comment]
Lukker denne grunnet #153 og #154
