### ISSUE TITLE
Bug i UserEvent

### ISSUE THREAD

**Issue by Zenjjim** [tihlde/API#121]
Hvis et medlem er registrert som ankommet til et event, er det ikke mulig å markere de som "ikke ankommet" i etterkant. Feilmeldingen er ``` detail: "User already attended" ```.

**Comment by olros** [comment]
Hvorfor skal man få lov til å fjerne medlemmer som har ankommet?

**Comment by Zenjjim** [comment]
Hvis et medlem er registrert ved feil, skal det være mulig å undo dette.

**Comment by olros** [comment]
Men det funker vel å markere de som "Ikke ankommet" og så fjerne de?

**Comment by Zenjjim** [comment]
Ja, my bad. Er vel det å markere  "Ikke ankommet" som ikke  fungerer

**Comment by Eirsteir** [comment]
Lukker denne siden det er gjort
